networks:
  cv-ideal-network:
    driver: bridge

services:
  backend:
    container_name: cvIdeal_api
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - cv-ideal-network
    command: >
      sh -c "yarn dev"
    volumes:
      - ./:/src 
      - ./node_modules:/src/node_modules
    depends_on:
      - database
  

  database:
    container_name: cvIdeal_database
    image: postgres
    restart: always
    env_file:
      - .env 
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE} 
    networks:
      - cv-ideal-network
    command: -p ${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data