networks:
  cv-ideal:
    name: cv-ideal
    driver: bridge


services:
  backend:
    container_name: cvIdeal_api
    restart: always
    env_file: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - cv-ideal
    environment:
      WAIT_HOSTS: database:${DB_PORT}
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    command: >
      sh -c "
      /wait && 
      yarn ${ENVIRONMENT}"
    depends_on:
      - database
    volumes:
      - ./:/usr/src
      - ./node_modules:/usr/src/node_modules

  database:
    container_name: cvIdeal_database
    image: postgres
    restart: always
    env_file:
      - .env 
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    networks:
      - cv-ideal
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE} 
    command: -p ${DB_PORT}
    
