networks:
  mtd-network:
    name: mtd-network
    driver: bridge


services:
  backend:
    container_name: mtd_api
    restart: always
    env_file: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - mtd-network
    command: yarn dev
    depends_on:
      - database
    volumes:
      - ./:/usr/src
      - ./node_modules:/usr/src/node_modules

  database:
    container_name: mtd_database
    image: postgres
    restart: always
    env_file:
      - .env 
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    networks:
      - mtd-network
    environment:
      POSTGRES_DB: ${DB_DATABASE} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - ${REDIS_PORT}:6379 # Fixando a porta interna do Redis para 6379
    command: redis-server --appendonly yes
    networks:
      - mtd-network
    
